# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import proxima.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок страницы')),
                ('photo', models.ImageField(upload_to=proxima.utils.models.PathRename('about'), verbose_name='Фото под заголовком')),
                ('block1_pretext', models.TextField(verbose_name='Текст цитаты')),
                ('block1_text', models.TextField(verbose_name='Основной текст')),
                ('block2_title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('block2_text', models.TextField(verbose_name='Основной текст')),
                ('block2_quote', models.TextField(verbose_name='Текст цитаты')),
                ('block2_text2', models.TextField(verbose_name='Основной текст 2')),
                ('block3_title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('block3_text', models.TextField(verbose_name='Основной текст')),
                ('block4_title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('block4_subtitle1', models.CharField(max_length=300, verbose_name='Первый подзаголовок')),
                ('block4_item1', models.TextField(verbose_name='Текст пункта 1')),
                ('block4_item2', models.TextField(verbose_name='Текст пункта 2')),
                ('block4_subtitle2', models.CharField(max_length=300, verbose_name='Второй подзаголовок')),
                ('block4_item3', models.TextField(verbose_name='Текст пункта 3')),
                ('block4_item4', models.TextField(verbose_name='Текст пункта 4')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_subtext', models.CharField(max_length=40, verbose_name='Подзаголовок слайда')),
                ('second_text', models.TextField(max_length=180, verbose_name='Заголовок слайда')),
                ('second_subtext', models.CharField(max_length=120, verbose_name='Текст справа от кнопки')),
                ('third_text', models.TextField(max_length=170, verbose_name='Заголовок слайда')),
                ('third_bg', models.ImageField(upload_to=proxima.utils.models.PathRename('mainpage'), verbose_name='Фоновое изображение')),
                ('third_bg_mobile', models.ImageField(upload_to=proxima.utils.models.PathRename('mainpage'), verbose_name='Фоновое изображение для адаптива')),
                ('fourth_text', models.TextField(max_length=105, verbose_name='Заголовок слайда')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='MainPageLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to=proxima.utils.models.PathRename('mainpage/logos'), verbose_name='Изображение')),
                ('position', models.CharField(default=1, max_length=10, verbose_name='Позиция')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.MainPage', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Логотип на главной',
                'verbose_name_plural': 'Логотипы на главной',
                'ordering': ('position',),
            },
        ),
    ]
