# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import proxima.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default=1, max_length=10, verbose_name='Позиция')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Направление деятельности',
                'verbose_name_plural': 'Направления деятельности',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=proxima.utils.models.PathRename('team'), verbose_name='Фото превью')),
                ('name', models.CharField(max_length=200, verbose_name='Имя и фамилия')),
                ('job', models.CharField(max_length=200, verbose_name='Должность')),
                ('main_photo', models.ImageField(upload_to=proxima.utils.models.PathRename('team'), verbose_name='Основное фото')),
                ('pretext', models.TextField(verbose_name='Текст цитаты')),
                ('position', models.CharField(default=1, max_length=10, verbose_name='Позиция')),
                ('actions', models.ManyToManyField(to='pages.ActionDirection')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='PersonBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default=1, max_length=10, verbose_name='Позиция')),
                ('period', models.CharField(blank=True, max_length=200, verbose_name='Период')),
                ('text', models.TextField(verbose_name='Текст')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Person', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Пункт биографии',
                'verbose_name_plural': 'Пункты биографии',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок страницы')),
                ('photo', models.ImageField(upload_to=proxima.utils.models.PathRename('team'), verbose_name='Фото под заголовком')),
                ('pretext', models.TextField(verbose_name='Текст цитаты')),
                ('people', models.ManyToManyField(to='pages.Person')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
