# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import proxima.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_actiondirection_person_personbio_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок страницы')),
                ('photo', models.ImageField(upload_to=proxima.utils.models.PathRename('career'), verbose_name='Фото под заголовком')),
                ('pretext', models.TextField(verbose_name='Текст цитаты')),
                ('specialists_text', models.TextField(verbose_name='Текст «Специалистам»')),
                ('students_text', models.TextField(verbose_name='Текст «Студентам»')),
            ],
            options={
                'verbose_name': 'Карьера',
                'verbose_name_plural': 'Карьера',
            },
        ),
        migrations.CreateModel(
            name='CareerAdvantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default=1, max_length=10, verbose_name='Позиция')),
                ('text', models.TextField(verbose_name='Текст')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Career', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Приемущество',
                'verbose_name_plural': 'Приемущества',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='CareerDemands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default=1, max_length=10, verbose_name='Позиция')),
                ('text', models.TextField(verbose_name='Текст')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Career', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Требование',
                'verbose_name_plural': 'Требования',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('file', models.FileField(upload_to=proxima.utils.models.PathRename('resume'), verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
