# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20171121_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondirection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='person',
            name='actions',
            field=models.ManyToManyField(blank=True, to='pages.ActionDirection'),
        ),
    ]
