# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20171121_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
