# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Documentation', verbose_name='Страница'),
        ),
    ]
