# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import proxima.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20171121_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок страницы')),
                ('photo', models.ImageField(upload_to=proxima.utils.models.PathRename('career'), verbose_name='Фото под заголовком')),
                ('pretext', models.TextField(verbose_name='Текст цитаты')),
                ('block1_title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('block1_subtitle', models.CharField(max_length=300, verbose_name='Подзаголовок')),
                ('block1_text', models.TextField(verbose_name='Текст')),
                ('block2_subtitle', models.CharField(max_length=300, verbose_name='Подзаголовок')),
                ('block2_item1', models.TextField(verbose_name='Текст пункта 1')),
                ('block2_item2', models.TextField(verbose_name='Текст пункта 2')),
                ('block2_item3', models.TextField(verbose_name='Текст пункта 3')),
                ('block3_subtitle', models.CharField(max_length=300, verbose_name='Подзаголовок')),
                ('block3_text', models.TextField(verbose_name='Текст')),
                ('block4_subtitle', models.CharField(max_length=300, verbose_name='Подзаголовок')),
                ('block4_text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Активы',
                'verbose_name_plural': 'Активы',
            },
        ),
    ]
