# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpage',
            options={'verbose_name': 'Страница проектов', 'verbose_name_plural': 'Страница проектов'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='page',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='projects',
            field=models.ManyToManyField(blank=True, to='pages.Project'),
        ),
    ]
