# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20171122_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('n', 'Новости'), ('a', 'Аналитические и экспертные материалы')], default='n', max_length=1, verbose_name='Категория'),
        ),
    ]
