# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'Страница новостей', 'verbose_name_plural': 'Страница новостей'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='page',
        ),
    ]
