# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20171123_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='category',
            new_name='type',
        ),
    ]
