# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20171127_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='first_subtext',
            field=models.CharField(max_length=300, verbose_name='Подзаголовок слайда'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='fourth_text',
            field=models.TextField(verbose_name='Заголовок слайда'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_subtext',
            field=models.CharField(max_length=300, verbose_name='Текст справа от кнопки'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='second_text',
            field=models.TextField(verbose_name='Заголовок слайда'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='third_text',
            field=models.TextField(verbose_name='Заголовок слайда'),
        ),
    ]
