# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import proxima.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20171206_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to=proxima.utils.models.PathRename('team'), verbose_name='Основное фото'),
        ),
    ]
