# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20171206_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О компании', 'verbose_name_plural': '2. О компании'},
        ),
        migrations.AlterModelOptions(
            name='actiondirection',
            options={'ordering': ('position',), 'verbose_name': 'Направление деятельности', 'verbose_name_plural': '10. Направления деятельности'},
        ),
        migrations.AlterModelOptions(
            name='actives',
            options={'verbose_name': 'Активы', 'verbose_name_plural': '8. Активы'},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'Карьера', 'verbose_name_plural': '5. Карьера'},
        ),
        migrations.AlterModelOptions(
            name='documentation',
            options={'verbose_name': 'Документация', 'verbose_name_plural': '7. Документация'},
        ),
        migrations.AlterModelOptions(
            name='expertise',
            options={'verbose_name': 'Экспертиза', 'verbose_name_plural': '9. Экспертиза'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('position',), 'verbose_name': 'Сотрудник', 'verbose_name_plural': ' 4. Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': '6. Резюме'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': '3. Команда'},
        ),
    ]
