# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20171206_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiondirection',
            options={'ordering': ('position',), 'verbose_name': 'Направление деятельности', 'verbose_name_plural': ' 10. Направления деятельности'},
        ),
    ]
