# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20171206_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О компании', 'verbose_name_plural': ' 2. О компании'},
        ),
        migrations.AlterModelOptions(
            name='actiondirection',
            options={'ordering': ('position',), 'verbose_name': 'Направление деятельности', 'verbose_name_plural': '10. Направления деятельности'},
        ),
        migrations.AlterModelOptions(
            name='actives',
            options={'verbose_name': 'Активы', 'verbose_name_plural': ' 8. Активы'},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'Карьера', 'verbose_name_plural': ' 5. Карьера'},
        ),
        migrations.AlterModelOptions(
            name='expertise',
            options={'verbose_name': 'Экспертиза', 'verbose_name_plural': ' 9. Экспертиза'},
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': ' 1. Главная страница'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': ' 6. Резюме'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': ' 3. Команда'},
        ),
    ]
