# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20171206_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': '16. Контакты'},
        ),
        migrations.AlterModelOptions(
            name='documentation',
            options={'verbose_name': 'Документация', 'verbose_name_plural': ' 7. Документация'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ('position',), 'verbose_name': 'Отрасль', 'verbose_name_plural': '13. Отрасли'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date',), 'verbose_name': 'Новость', 'verbose_name_plural': '15. Новости'},
        ),
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'Страница новостей', 'verbose_name_plural': '14. Страница новостей'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('position',), 'verbose_name': 'Проект', 'verbose_name_plural': '12. Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectpage',
            options={'verbose_name': 'Страница проектов', 'verbose_name_plural': '11. Страница проектов'},
        ),
    ]
