# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20171206_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='project',
        ),
        migrations.AddField(
            model_name='news',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст на кнопке'),
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ссылка'),
        ),
    ]
