# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20171207_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ссылка (для ссылки на внутренние страницы надо начинать с "/")'),
        ),
    ]
