# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import proxima.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20171207_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to=proxima.utils.models.PathRename('news/previews'), verbose_name='Фото на ховере превью'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo1',
            field=models.ImageField(blank=True, upload_to=proxima.utils.models.PathRename('news/photos'), verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pretext',
            field=models.TextField(blank=True, verbose_name='Текст цитаты'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle1',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок 1'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle2',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок 2'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text1',
            field=models.TextField(blank=True, verbose_name='Текст 1'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text2',
            field=models.TextField(blank=True, verbose_name='Текст 2'),
        ),
    ]
