# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20180312_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geo_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='География проекта текст'),
        ),
        migrations.AddField(
            model_name='project',
            name='inv_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Инвестиции PCG текст'),
        ),
        migrations.AddField(
            model_name='project',
            name='per_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Период реализации текст'),
        ),
    ]
