# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20180313_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='Завершен?'),
        ),
    ]
