# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_preview',
            field=models.CharField(blank=True, max_length=350, verbose_name='Название в превью'),
        ),
    ]
