# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_auto_20180813_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='block1_pretext_en',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='about',
            name='block1_pretext_ru',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='about',
            name='block1_text_en',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='about',
            name='block1_text_ru',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='about',
            name='block2_quote_en',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='about',
            name='block2_quote_ru',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='about',
            name='block2_text2_en',
            field=models.TextField(null=True, verbose_name='Основной текст 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='block2_text2_ru',
            field=models.TextField(null=True, verbose_name='Основной текст 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='block2_text_en',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='about',
            name='block2_text_ru',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='about',
            name='block2_title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about',
            name='block2_title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about',
            name='block3_text_en',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='about',
            name='block3_text_ru',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='about',
            name='block3_title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about',
            name='block3_title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_item1_en',
            field=models.TextField(null=True, verbose_name='Текст пункта 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_item1_ru',
            field=models.TextField(null=True, verbose_name='Текст пункта 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_item2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст пункта 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_item2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст пункта 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_item3_en',
            field=models.TextField(null=True, verbose_name='Текст пункта 3'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_item3_ru',
            field=models.TextField(null=True, verbose_name='Текст пункта 3'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_item4_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст пункта 4'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_item4_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст пункта 4'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_subtitle1_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Первый подзаголовок'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_subtitle1_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Первый подзаголовок'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_subtitle2_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Второй подзаголовок'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_subtitle2_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Второй подзаголовок'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about',
            name='block4_title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Заголовок страницы'),
        ),
    ]
