# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_auto_20180814_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pretext_en',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='team',
            name='pretext_ru',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='team',
            name='title_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='team',
            name='title_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Заголовок страницы'),
        ),
    ]
