# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_auto_20180814_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondirection',
            name='pretext_en',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='actiondirection',
            name='pretext_ru',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='actiondirection',
            name='subtitle_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='actiondirection',
            name='subtitle_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='actiondirection',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='actiondirection',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='actiondirection',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='actiondirection',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
