# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_auto_20180814_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondirectionitems',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='actiondirectionitems',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
