# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_auto_20180814_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='job_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='person',
            name='job_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя и фамилия'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя и фамилия'),
        ),
        migrations.AddField(
            model_name='person',
            name='pretext_en',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='person',
            name='pretext_ru',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='personbio',
            name='period_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Период'),
        ),
        migrations.AddField(
            model_name='personbio',
            name='period_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Период'),
        ),
        migrations.AddField(
            model_name='personbio',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='personbio',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
