# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_auto_20180814_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='pretext_en',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='career',
            name='pretext_ru',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='career',
            name='specialists_text_en',
            field=models.TextField(null=True, verbose_name='Текст «Специалистам»'),
        ),
        migrations.AddField(
            model_name='career',
            name='specialists_text_ru',
            field=models.TextField(null=True, verbose_name='Текст «Специалистам»'),
        ),
        migrations.AddField(
            model_name='career',
            name='students_text_en',
            field=models.TextField(null=True, verbose_name='Текст «Студентам»'),
        ),
        migrations.AddField(
            model_name='career',
            name='students_text_ru',
            field=models.TextField(null=True, verbose_name='Текст «Студентам»'),
        ),
        migrations.AddField(
            model_name='career',
            name='title_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='career',
            name='title_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='careeradvantages',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='careeradvantages',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='careerdemands',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='careerdemands',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
