# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_auto_20180814_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название отрасли'),
        ),
        migrations.AddField(
            model_name='industry',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название отрасли'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='project',
            name='geo_en',
            field=models.CharField(max_length=15, null=True, verbose_name='География проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='geo_ru',
            field=models.CharField(max_length=15, null=True, verbose_name='География проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='geo_text_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='География проекта текст'),
        ),
        migrations.AddField(
            model_name='project',
            name='geo_text_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='География проекта текст'),
        ),
        migrations.AddField(
            model_name='project',
            name='inv_en',
            field=models.CharField(max_length=15, null=True, verbose_name='Инвестиции PCG'),
        ),
        migrations.AddField(
            model_name='project',
            name='inv_ru',
            field=models.CharField(max_length=15, null=True, verbose_name='Инвестиции PCG'),
        ),
        migrations.AddField(
            model_name='project',
            name='inv_text_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Инвестиции PCG текст'),
        ),
        migrations.AddField(
            model_name='project',
            name='inv_text_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Инвестиции PCG текст'),
        ),
        migrations.AddField(
            model_name='project',
            name='per_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Период реализации'),
        ),
        migrations.AddField(
            model_name='project',
            name='per_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Период реализации'),
        ),
        migrations.AddField(
            model_name='project',
            name='per_text_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Период реализации текст'),
        ),
        migrations.AddField(
            model_name='project',
            name='per_text_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Период реализации текст'),
        ),
        migrations.AddField(
            model_name='project',
            name='pretext_en',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='project',
            name='pretext_ru',
            field=models.TextField(null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст основной'),
        ),
        migrations.AddField(
            model_name='project',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст основной'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=350, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_preview_en',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Название в превью'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_preview_ru',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Название в превью'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=350, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст основной'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст основной'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок страницы'),
        ),
    ]
