# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_auto_20180814_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст на кнопке'),
        ),
        migrations.AddField(
            model_name='news',
            name='button_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст на кнопке'),
        ),
        migrations.AddField(
            model_name='news',
            name='pretext_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='news',
            name='pretext_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст цитаты'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle1_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle1_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle2_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle2_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='text1_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='text1_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='text2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='text2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Основной текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=240, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=240, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='title_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='title_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Заголовок страницы'),
        ),
    ]
