# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_auto_20180814_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(max_length=120, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Адрес'),
        ),
    ]
