# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-09 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_auto_20180814_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subtitle3',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок 3'),
        ),
    ]
